name = "ShaderSandbox"
uuid = "3d788dd4-5a26-45dd-b01b-e0b62f1919cb"
version = "2.0.1"
authors = ["Szűcs Gergely <p6odrh@inf.elte.hu>"]

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
JuliaGLM = "d62f3426-b328-4065-b1cd-fa40c3c5e4f7"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
ShaderTranspiler = "5f1345c2-4092-4c5f-a4c1-0bd0b6ca6a9b"
stc_jll = "8dead81b-3450-5e2f-948b-0f2a405f2b3d"

[sources]
JuliaGLM = {rev = "glsl-functions", url = "https://github.com/Csabix/JuliaGLM"}
ShaderTranspiler = {url = "https://github.com/ShaderTranspiler/ShaderTranspiler.jl"}
stc_jll = {url = "https://github.com/ShaderTranspiler/stc_jll.jl"}

[compat]
CImGui = "7.1.0"
Dates = "1.11.0"
GLFW = "3.4.6"
JuliaGLM = "0.0.1"
ModernGL = "1.1.8"
ShaderTranspiler = "1.0.0"
stc_jll = "1.0.0"

[apps.shader-sandbox]
